### ISSUE TITLE
UGT seems to require a certain folder structure

### ISSUE THREAD

**Issue by kidkwazine** [orels1/UdonGraphTweaks#1]
You the GOAT for making this. 🙌🏻

Just wanted to point out a possible QoL fix in the repo (or maybe in the readme) that I stumbled into:

UGT expects everything to be in `Assets/Editor/UGT/...` or it errors out. Current repo doesn't have this expected UGT folder structure or it isn't listed in the readme that it needs to be in this folder.

Creating the folder myself and throwing everything in there made everything function properly 👍🏻
love u

**Comment by orels1** [comment]
Ooh! You're right. I totally forgot about that 💀 
I'll try to update the docs and the script
